import type { Metadata } from 'next'
import { SolutionPageLayout } from '@/components/seo/SolutionPageLayout'

export const metadata: Metadata = {
  title: 'Online Quiz Maker — Free Quiz Builder with 11 Question Types',
  description:
    'Free online quiz maker. Build quizzes with 11 question types, images, explanations, and Bloom\'s Taxonomy tagging. Launch live, assign as homework, or embed. INR billing.',
  alternates: { canonical: '/quiz-maker' },
  keywords: [
    'quiz maker',
    'online quiz maker',
    'free quiz maker',
    'quiz builder',
    'create quiz online',
    'quiz creator',
  ],
}

export default function QuizMakerPage() {
  return (
    <SolutionPageLayout
      slug="quiz-maker"
      h1="Online Quiz Maker"
      tagline="A free quiz maker that's fast to build with and pleasant to run. 11 question types, AI assist, and launch modes for every use case."
      intro="Build quizzes the way you want — manually in a rich editor, generated by AI from a topic or PDF, or imported from your existing content. Quizotic's quiz maker handles everything from a quick classroom check to a formal assessment with shuffled questions and a secure time window. Every question supports images, explanations, and Bloom tagging out of the box."
      features={[
        { title: 'Rich question editor', description: 'Text, images, explanations, multiple correct answers, partial credit — full control per question.' },
        { title: 'AI assist built in', description: 'Let the AI draft the quiz from your notes; polish and publish. Or start blank and build manually.' },
        { title: 'Launch modes', description: 'Live multiplayer, self-paced share link, or formal assessment with shuffling and a time window.' },
        { title: 'Reuse and remix', description: 'Duplicate quizzes, move questions between quizzes, tag with folders and topics.' },
        { title: 'Team collaboration', description: 'Co-authors can edit the same quiz. Changes sync in real time, comments stay per question.' },
        { title: 'INR billing', description: 'All plans in Indian Rupees with UPI and card support. Generous free tier.' },
      ]}
      steps={[
        { title: 'Start a new quiz', description: 'Choose blank, AI-generated, or import from PDF. Add a title and topic.' },
        { title: 'Add questions', description: 'Pick from 11 question types. Add images, explanations, and Bloom tags per question.' },
        { title: 'Pick a launch mode', description: 'Live, self-paced, or assessment. Share the PIN or link.' },
      ]}
      faqs={[
        {
          question: 'Is the quiz maker really free?',
          answer: 'Yes. You can build unlimited quizzes and run live sessions with up to 10 participants on the free plan. Pro and Team unlock larger audiences and advanced features.',
        },
        {
          question: 'Can I add images to my questions?',
          answer: 'Yes. Upload images to any question or answer option; images are hosted on a CDN for fast classroom loading.',
        },
        {
          question: 'Can I reuse questions across quizzes?',
          answer: 'Yes. Duplicate quizzes or move individual questions between quizzes. Your question bank grows over time.',
        },
        {
          question: 'Does it support Hindi and Indian languages?',
          answer: 'Yes. The editor supports Unicode — type in Hindi, Tamil, Bengali, and other Indian scripts directly. Participants see the same on their devices.',
        },
        {
          question: 'Can multiple teachers edit the same quiz?',
          answer: 'Yes on Team plans. Co-authors can edit in real time, comment per question, and see edit history.',
        },
      ]}
      related={[
        { title: 'AI Quiz Generator', href: '/ai-quiz-generator', description: 'Let AI draft quizzes from your topic or PDF.' },
        { title: 'Live Quiz', href: '/live-quiz', description: 'Run your quiz as a live multiplayer game.' },
        { title: 'PDF to Quiz', href: '/pdf-to-quiz', description: 'Import a PDF and get a quiz in minutes.' },
        { title: 'All features', href: '/features', description: 'Full feature list and question types.' },
        { title: 'Pricing', href: '/pricing', description: 'Free, Pro, Team — priced in INR.' },
      ]}
      ctaLabel="Start building your quiz free →"
    />
  )
}
