import type { Metadata } from 'next'
import { SolutionPageLayout } from '@/components/seo/SolutionPageLayout'

export const metadata: Metadata = {
  title: 'Online Quiz Maker — Free Quiz Builder with 11 Question Types',
  description:
    'Free online quiz maker. Build quizzes with 11 question types, images, explanations, and Bloom\'s Taxonomy tagging. Launch live, assign as homework, or embed. INR billing.',
  alternates: { canonical: '/quiz-maker' },
  keywords: [
    'quiz maker',
    'online quiz maker',
    'free quiz maker',
    'quiz builder',
    'create quiz online',
    'quiz creator',
  ],
}

export default function QuizMakerPage() {
  return (
    <SolutionPageLayout
      slug="quiz-maker"
      h1="Online Quiz Maker"
      tagline="A free quiz maker that's fast to build with and pleasant to run. 11 question types, AI assist, and launch modes for every use case."
      intro="Build quizzes the way you want — manually in a rich editor, generated by AI from a topic or PDF, or imported from your existing content. Quizotic's quiz maker handles everything from a quick classroom check to a formal assessment with shuffled questions and a secure time window. Every question supports images, explanations, and Bloom tagging out of the box."
      tldr={[
        '11 question types: MCQ, multi-select, true/false, poll, open-ended, word cloud, Q&A, rating, ranking, case study, drawing.',
        'AI assistant drafts a full quiz from any topic or PDF in under 30 seconds.',
        'Three launch modes: live multiplayer, self-paced link, or formal assessment with shuffling.',
        'Free plan: unlimited quiz builds, live sessions up to 10 participants.',
        'INR billing, UPI accepted — no international card required.',
      ]}
      features={[
        { title: 'Rich question editor', description: 'Text, images, explanations, multiple correct answers, partial credit — full control per question.' },
        { title: 'AI assist built in', description: 'Let the AI draft the quiz from your notes; polish and publish. Or start blank and build manually.' },
        { title: 'Launch modes', description: 'Live multiplayer, self-paced share link, or formal assessment with shuffling and a time window.' },
        { title: 'Reuse and remix', description: 'Duplicate quizzes, move questions between quizzes, tag with folders and topics.' },
        { title: 'Team collaboration', description: 'Co-authors can edit the same quiz. Changes sync in real time, comments stay per question.' },
        { title: 'INR billing', description: 'All plans in Indian Rupees with UPI and card support. Generous free tier.' },
      ]}
      steps={[
        { title: 'Start a new quiz', description: 'Choose blank, AI-generated, or import from PDF. Add a title and topic.' },
        { title: 'Add questions', description: 'Pick from 11 question types. Add images, explanations, and Bloom tags per question.' },
        { title: 'Pick a launch mode', description: 'Live, self-paced, or assessment. Share the PIN or link.' },
      ]}
      audienceCards={[
        { title: 'Teachers & Educators', description: 'Weekly chapter quizzes, term-end revisions, parent-meeting reports. AI writes the questions; you launch in 10 minutes.', href: '/for/teachers' },
        { title: 'Corporate L&D Teams', description: 'Onboarding assessments, compliance checks, live workshop Q&A — all in one deck with team reports.', href: '/for/corporate-trainers' },
        { title: 'Event Hosts & Trainers', description: 'Live trivia nights, conference icebreakers, hackathon quizzes — up to 200 participants per session on Pro.', href: '/for/event-hosts' },
      ]}
      comparisonSection={{
        heading: 'Quizotic vs other quiz makers',
        rows: [
          { feature: 'Question types', quizotic: '11 (MCQ, word cloud, ranking, drawing, more)', competitor: 'Google Forms: 9; Typeform: 10; Kahoot: 4', winner: 'quizotic' },
          { feature: 'AI quiz generation', quizotic: 'Free (30 Qs/month)', competitor: 'Google Forms: No; Typeform: No; Kahoot: Paid', winner: 'quizotic' },
          { feature: 'Live multiplayer with leaderboard', quizotic: 'Yes — Kahoot-style', competitor: 'Google Forms: No; Typeform: No; Kahoot: Yes', winner: 'tie' },
          { feature: 'INR billing + UPI', quizotic: 'Yes', competitor: 'All USD-billed', winner: 'quizotic' },
          { feature: 'Bloom\'s Taxonomy tagging', quizotic: 'Built-in', competitor: 'None', winner: 'quizotic' },
          { feature: 'Per-student diagnostic reports', quizotic: 'Yes (Bloom + Confidence Grid)', competitor: 'Google Forms: Basic; Others: None', winner: 'quizotic' },
          { feature: 'Free participant limit', quizotic: '10 per session', competitor: 'Google Forms: Unlimited (responses only); Kahoot: 10–40', winner: 'tie' },
          { feature: 'Brand / audience recognition', quizotic: 'Growing (India)', competitor: 'Google Forms & Kahoot widely known', winner: 'competitor' },
        ],
      }}
      faqs={[
        {
          question: 'Is the quiz maker really free?',
          answer: 'Yes. You can build unlimited quizzes and run live sessions with up to 10 participants on the free plan. Pro and Team unlock larger audiences and advanced features.',
        },
        {
          question: 'Can I add images to my questions?',
          answer: 'Yes. Upload images to any question or answer option; images are hosted on a CDN for fast classroom loading.',
        },
        {
          question: 'Can I reuse questions across quizzes?',
          answer: 'Yes. Duplicate quizzes or move individual questions between quizzes. Your question bank grows over time.',
        },
        {
          question: 'Does it support Hindi and Indian languages?',
          answer: 'Yes. The editor supports Unicode — type in Hindi, Tamil, Bengali, and other Indian scripts directly. Participants see the same on their devices.',
        },
        {
          question: 'Can multiple teachers edit the same quiz?',
          answer: 'Yes on Team plans. Co-authors can edit in real time, comment per question, and see edit history.',
        },
        {
          question: 'What question types does Quizotic support?',
          answer: '11 types: Multiple Choice (MCQ), Multi-select, True/False, Open-ended text, Poll (no correct answer), Word cloud, Q&A with upvotes, Rating scale, Ranking, Case study (multi-part MCQ), and Drawing response. Mix and match in any order within one quiz.',
        },
        {
          question: 'Can I randomise question order and answer options?',
          answer: 'Yes. In formal assessment mode, questions and/or answer options shuffle per student. Useful for classroom tests to prevent copying.',
        },
        {
          question: 'Can I add a time limit per question?',
          answer: 'Yes. Set a countdown timer per question (5, 10, 20, 30, 60, 90, 120 seconds). In live mode, the speed bonus awards extra points for faster correct answers.',
        },
        {
          question: 'Does Quizotic support partial credit?',
          answer: 'Yes for multi-select questions. You define which combination of correct choices earns full, partial, or zero credit.',
        },
        {
          question: 'Can I share a quiz publicly without making participants sign in?',
          answer: 'Yes. A shareable link lets participants join with just their name — no Quizotic account required. For formal assessments, you can optionally require login for accountability.',
        },
        {
          question: 'How do I export quiz results?',
          answer: 'Download a CSV with per-student scores, per-question accuracy, and Bloom breakdown. Import into Google Sheets, Excel, or your LMS gradebook.',
        },
        {
          question: 'Is there a question bank I can pull from?',
          answer: 'Quizotic has 50+ ready-made templates in the Templates Gallery and a growing NCERT chapter library. The AI generator supplements both — generate fresh questions from any source on demand.',
        },
      ]}
      related={[
        { title: 'AI Quiz Generator', href: '/ai-quiz-generator', description: 'Let AI draft quizzes from your topic or PDF.' },
        { title: 'Live Quiz', href: '/live-quiz', description: 'Run your quiz as a live multiplayer game.' },
        { title: 'PDF to Quiz', href: '/pdf-to-quiz', description: 'Import a PDF and get a quiz in minutes.' },
        { title: 'All features', href: '/features', description: 'Full feature list and question types.' },
        { title: 'Pricing', href: '/pricing', description: 'Free, Pro, Team — priced in INR.' },
      ]}
      ctaLabel="Start building your quiz free →"
    />
  )
}
